export const URL = "https://api.themoviedb.org";
export const TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzMzE3NTZhMDY0ZjA0OGU5ZDdlZjc1ODMyYzhlNjM3MyIsInN1YiI6IjYzYzg0YTcxYWJkZWMwMDBhZTI0ODI0OSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AGauQWfIsXUjaf1e49zGS3LgU9W4VKYu298u0P_VRkw";
